### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by omprakashgupta1995** [Tekno-Point/motilaloswal-nbfc-website-poc-en#1]
### Description
Develop Header for desktop and mobile with navigation

### Requirements
- [ ] **Requirement 1 :** Create the below Header for desktop and mobile 
![image](https://github.com/user-attachments/assets/b6ebd174-6dac-47e9-955c-4a5d53ede00b)

![image](https://github.com/user-attachments/assets/bf6d0709-e6a0-40c8-9619-7ef9d9c04b0b)

- [ ] **Requirement 2:** Create the navigation for the headers
![image](https://github.com/user-attachments/assets/4a5e512f-d907-4c10-a75a-d078829a045f)
![image](https://github.com/user-attachments/assets/95ed19d3-b1de-4911-ac42-2feb0023de7f)

### Acceptance Criteria
- [ ] **Criterion 1:** On Hover Navigation should be open on the desktop.
- [ ] **Criterion 2:** On click on Hamburger Navigation should be open on the mobile.
- [ ] **Criterion 3:** On clicking on the Navigation sub-item it should be redirected to the respective page.

### Additional Context
Please refer https://www.motilaloswal.com/ 

### Dependencies
- NA

### Resources
- https://www.motilaloswal.com/ 

### Assignees
- **Assigned to:** @omprakashgupta1995 
- **Reviewers:** @Swapnil1194 

### Labels
- NA
### Milestone
- NA
### Due Date
- NA
