### ISSUE TITLE
Hero Banner

### ISSUE THREAD

**Issue by omprakashgupta1995** [Tekno-Point/motilaloswal-nbfc-website-poc-en#3]
### Description
Develop Hero Banner for desktop and mobile with typing and backslash animation.

### Requirements
- [ ] **Requirement 1:** Create the below Hero Banner for desktop and mobile 
Desktop :
![image](https://github.com/user-attachments/assets/477df6d3-1dfc-4395-83d9-aa9381ab5d5f)
Mobile :
![image](https://github.com/user-attachments/assets/e8822222-4672-495a-9ddc-ab2d677ec042)

- [ ] **Requirement 2:** Create the authorable background image for the hero banner.
Image URL - https://dbs7qpzv4mcv.cloudfront.net/background3.webp

- [ ] **Requirement 3:** Add the Animation on the first text 
Refer - https://www.motilaloswal.com/

### Acceptance Criteria
- [ ] **Criterion 1:** The First Line should have an animation with backslash and typing.
- [ ] **Criterion 2:** Background Image will be authorable.

### Additional Context
Please refer https://www.motilaloswal.com/ 

### Dependencies
- NA

### Resources
- https://www.motilaloswal.com/ 

### Assignees
- **Assigned to:** @omprakashgupta1995 
- **Reviewers:** @Swapnil1194 

### Labels
- NA
### Milestone
- NA
### Due Date
- NA
