### ISSUE TITLE
Open Demat Account Form

### ISSUE THREAD

**Issue by omprakashgupta1995** [Tekno-Point/motilaloswal-nbfc-website-poc-en#4]
### Description
Develop an Open Demat Account Form with validation for desktop and mobile users.

### Requirements
- [ ] **Requirement 1:** Create the Open Demat Account Form below for desktop and mobile.
Mobile:
![image](https://github.com/user-attachments/assets/145213cb-7191-4d9d-a577-1640427c0c20)

Desktop :
![image](https://github.com/user-attachments/assets/435f271a-d5f6-46be-a36d-6f7eaaa964ac) ![image](https://github.com/user-attachments/assets/a026f0cf-5cae-4b1e-9467-461047ab84ec)

- [ ] **Requirement 2:** Form will be sticky on mobile view 
![image](https://github.com/user-attachments/assets/5c8c1a79-ae74-4126-bc96-5a90b0fac64f)

- [ ] **Requirement 3:** Form will be with hero banner section on desktop view 
![image](https://github.com/user-attachments/assets/39d00ab2-dc11-40da-a96e-b9160be5d94c)

- [ ] **Requirement 4:** On Form Submit below form modal should be open
![image](https://github.com/user-attachments/assets/c6bc08bd-adaf-4038-819a-65e9bb377a36)

### Acceptance Criteria
- [ ] **Criterion 1:** On Input Mobile Number should be validated with 10 digits.
- [ ] **Criterion 2:** On validation success open the modal which should have form and prefill validate mobile number
- [ ] **Criterion 3:** On validation fail to show the below error msg
![image](https://github.com/user-attachments/assets/e6a4e8c9-685a-4eb5-9362-60c964961d1a)

### Additional Context
Please refer https://www.motilaloswal.com/ 

### Dependencies
- NA

### Resources
- https://www.motilaloswal.com/ 

### Assignees
- **Assigned to:** @omprakashgupta1995 
- **Reviewers:** @Swapnil1194 

### Labels
- NA
### Milestone
- NA
### Due Date
- NA
